[target.thumbv6m-none-eabi]
runner = 'probe-rs run --chip STM32F051R8T6 --protocol swd --speed 1000'
#rustflags = [
 # "-C", "link-arg=--nmagic",
  #"-C", "link-arg=-Tlink.x",       // if we add this in this file we dont need build.rs because here it selt linking we are doing
  #"-C", "link-arg=-Tdefmt.x"       // but if we use build .rs it will give separate file clarity and relaeblity
#]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"